version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: clean-css
    versions:
    - 5.0.1
    - 5.1.0
    - 5.1.1
  - dependency-name: hexo
    versions:
    - 4.2.1
  - dependency-name: imagemin-pngquant
    versions:
    - 9.0.1
  - dependency-name: imagemin-svgo
    versions:
    - 8.0.0
